import type {KnownProjectSnapshot, Snapshot} from "../api/controlPlane";

const project = {
  id: "proj_test",
  name: "Test",
  path: "C:\\Users\\Liparakis\\Desktop\\Test",
  createdAt: "2026-09-10T00:00:00Z",
};

const additionalProjects: KnownProjectSnapshot[] = [
  ["proj_aurora", "Aurora pipeline", "C:\\Users\\Liparakis\\Desktop\\AuroraPipeline", "LIVE"],
  ["proj_beacon", "Beacon runtime", "C:\\Users\\Liparakis\\Desktop\\BeaconRuntime", "INACTIVE"],
  ["proj_cinder", "Cinder tools", "C:\\Users\\Liparakis\\Desktop\\CinderTools", "LIVE"],
  ["proj_delta", "Delta control", "C:\\Users\\Liparakis\\Desktop\\DeltaControl", "UNAVAILABLE"],
  ["proj_echo", "Echo telemetry", "C:\\Users\\Liparakis\\Desktop\\EchoTelemetry", "IDENTITY_MISMATCH"],
  ["proj_forge", "Forge workspace", "C:\\Users\\Liparakis\\Desktop\\ForgeWorkspace", "LIVE"],
  ["proj_grove", "Grove docs", "C:\\Users\\Liparakis\\Desktop\\GroveDocs", "INACTIVE"],
  ["proj_halo", "Halo gateway", "C:\\Users\\Liparakis\\Desktop\\HaloGateway", "LIVE"],
  ["proj_iris", "Iris checks", "C:\\Users\\Liparakis\\Desktop\\IrisChecks", "LIVE"],
  ["proj_joule", "Joule mesh", "C:\\Users\\Liparakis\\Desktop\\JouleMesh", "INACTIVE"],
  ["proj_kite", "Kite worker", "C:\\Users\\Liparakis\\Desktop\\KiteWorker", "LIVE"],
  ["proj_lumen", "Lumen service", "C:\\Users\\Liparakis\\Desktop\\LumenService", "UNAVAILABLE"],
].map(([id, name, path, status], index) => ({
  id,
  name,
  path,
  createdAt: `2026-09-${String(1 + index).padStart(2, "0")}T00:00:00Z`,
  firstObservedAt: `2026-09-${String(1 + index).padStart(2, "0")}T00:00:00Z`,
  lastObservedAt: `2026-09-10T0${index % 4 + 1}:20:00Z`,
  status: status as KnownProjectSnapshot["status"],
}));

export const mockSnapshot: Snapshot = {
  apiVersion: "v1",
  runtime: {
    status: "RUNNING",
    apiVersion: "v1",
    version: "0.1.0-dev",
    activeProjectCount: 7,
    headSequence: 42,
    activeAgentCount: 2,
    connectedPeerCount: 8,
    networkStatus: "CONNECTED",
    relayStatus: "DISABLED",
  },
  project,
  knownProjects: [
    {...project, status: "LIVE", firstObservedAt: "2026-09-10T00:00:00Z", lastObservedAt: "2026-09-10T02:45:00Z"},
    {
      id: "proj_vector",
      name: "Vector mesh",
      path: "C:\\Users\\Liparakis\\Desktop\\VectorMesh",
      createdAt: "2026-09-08T00:00:00Z",
      firstObservedAt: "2026-09-08T00:00:00Z",
      lastObservedAt: "2026-09-09T22:10:00Z",
      status: "INACTIVE",
    },
    ...additionalProjects,
  ],
  providers: [
    {id: "claude", supportLevel: "SUPPORTED", status: "READY"},
    {id: "codex", supportLevel: "SUPPORTED", status: "READY"},
  ],
  agents: [
    {
      id: "agent-planner-01",
      provider: "anthropic/claude-3-5-sonnet",
      goal: "Refactor AST parser",
      state: "CLAIM_HELD",
      lastVerifiedActivity: "2026-09-10T02:44:00Z",
      claims: [{kind: "file", value: "src/parser"}],
      currentWork: {
        intentId: "intent-planner-01",
        taskId: "task-001",
        goal: "Refactor AST parser",
        acceptance: "Parser tests remain green",
        status: "PLANNING",
        role: "planner",
        workGroupId: "wg-backend-refactor",
      },
      waitingOn: [],
    },
    {
      id: "code-executor-02",
      provider: "openai/gpt-4o",
      goal: "Refactor AST parser",
      state: "WAITING_DEP",
      lastVerifiedActivity: "2026-09-10T02:41:00Z",
      claims: [{kind: "file", value: "src/parser/tests"}],
      currentWork: null,
      waitingOn: ["wg-type-checker"],
    },
    {
      id: "test-runner-03",
      provider: "anthropic/claude-3-5-sonnet",
      goal: "Run test suite",
      state: "LIVE",
      lastVerifiedActivity: "2026-09-10T02:45:00Z",
      claims: [],
      currentWork: null,
      waitingOn: [],
    },
  ],
  workgroups: [
    {id: "wg-backend-refactor", status: "ACTIVE", version: 4, goal: "Refactor the parser safely", acceptance: "All parser checks pass", participants: ["agent-planner-01", "code-executor-02"]},
    {id: "wg-type-checker", status: "PLANNING", version: 2, goal: "Strengthen type checks", acceptance: "Type diagnostics are published", participants: ["test-runner-03"]},
  ],
  claims: [
    {intentId: "intent-planner-01", participant: "agent-planner-01", workGroupId: "wg-backend-refactor", role: "planner", state: "CLAIM_HELD", selectors: [{kind: "file", value: "src/parser"}], conflicts: []},
    {intentId: "intent-executor-02", participant: "code-executor-02", workGroupId: "wg-backend-refactor", role: "executor", state: "WAITING_DEP", selectors: [{kind: "file", value: "src/parser/tests"}], conflicts: []},
  ],
  capabilities: [
    {
      handle: "cap-refactor-001",
      capability: "code.refactor",
      requester: "agent-planner-01",
      owner: "code-executor-02",
      state: "GRANTED",
      reason: "AST parser cleanup",
      createdAtEpochMillis: Date.parse("2026-09-10T02:30:00Z"),
      updatedAtEpochMillis: Date.parse("2026-09-10T02:40:00Z"),
      contract: {inputs: ["src/parser"], output: "Updated parser", requiredBehavior: "Preserve syntax nodes", acceptanceTests: ["parser suite"]},
    },
  ],
  tasks: [
    {id: "task-001", title: "AST Refactor", capability: "code.refactor", owner: "agent-planner-01"},
    {id: "task-002", title: "Type Generation", capability: "code.refactor", owner: "agent-planner-01"},
    {id: "task-003", title: "Error Map", capability: "code.executor", owner: "code-executor-02"},
  ],
  ownerships: [
    {capability: "code.refactor", taskId: "task-001", owner: "agent-planner-01", protectedScopes: ["src/parser"], intentVersion: 2},
  ],
  network: {
    status: "CONFIGURED",
    peers: [
      {nodeId: "peer_9x23a", sessionId: "session_001", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:40:00Z", authenticated: true, health: "HEALTHY"},
      {nodeId: "peer_3d9f0", sessionId: "session_002", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:42:00Z", authenticated: true, health: "HEALTHY"},
      {nodeId: "peer_71ab2", sessionId: "session_003", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:38:00Z", authenticated: true, health: "HEALTHY"},
      {nodeId: "peer_b4c8d", sessionId: "session_004", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:35:00Z", authenticated: true, health: "HEALTHY"},
      {nodeId: "peer_c8d31", sessionId: "session_005", liveness: "DEGRADED", usable: true, establishedAt: "2026-09-10T02:31:00Z", authenticated: true, health: "DEGRADED"},
      {nodeId: "peer_f120a", sessionId: "session_006", liveness: "UNREACHABLE", usable: false, establishedAt: "2026-09-10T02:28:00Z", authenticated: false, health: "UNREACHABLE"},
      {nodeId: "peer_4fe22", sessionId: "session_007", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:24:00Z", authenticated: true, health: "HEALTHY"},
      {nodeId: "peer_6aa90", sessionId: "session_008", liveness: "CONNECTED", usable: true, establishedAt: "2026-09-10T02:20:00Z", authenticated: true, health: "HEALTHY"},
    ],
    routes: [
      {kind: "DIRECT", destinationNodeId: "peer_9x23a", path: ["local", "peer_9x23a"], nextHop: "peer_9x23a", relayNodeId: ""},
      {kind: "PEER_TRANSIT", destinationNodeId: "peer_3d9f0", path: ["local", "peer_9x23a", "peer_3d9f0"], nextHop: "peer_9x23a", relayNodeId: ""},
      {kind: "DIRECT", destinationNodeId: "peer_71ab2", path: ["local", "peer_71ab2"], nextHop: "peer_71ab2", relayNodeId: ""},
      {kind: "PEER_TRANSIT", destinationNodeId: "peer_b4c8d", path: ["local", "peer_9x23a", "peer_b4c8d"], nextHop: "peer_9x23a", relayNodeId: ""},
      {kind: "DIRECT", destinationNodeId: "peer_c8d31", path: ["local", "peer_c8d31"], nextHop: "peer_c8d31", relayNodeId: ""},
      {kind: "RELAY", destinationNodeId: "peer_f120a", path: ["local", "relay_01", "peer_f120a"], nextHop: "relay_01", relayNodeId: "relay_01"},
      {kind: "PEER_TRANSIT", destinationNodeId: "peer_4fe22", path: ["local", "peer_3d9f0", "peer_4fe22"], nextHop: "peer_3d9f0", relayNodeId: ""},
      {kind: "DIRECT", destinationNodeId: "peer_6aa90", path: ["local", "peer_6aa90"], nextHop: "peer_6aa90", relayNodeId: ""},
    ],
    overlay: {
      status: "CONFIGURED",
      authorityNodeId: "peer_9x23a",
      revision: 3,
      memberCount: 9,
      expiresAt: "2026-09-10T04:00:00Z",
      members: [
        {nodeId: "peer_9x23a", status: "ACTIVE"},
        {nodeId: "peer_3d9f0", status: "ACTIVE"},
        {nodeId: "peer_71ab2", status: "ACTIVE"},
        {nodeId: "peer_b4c8d", status: "ACTIVE"},
        {nodeId: "peer_c8d31", status: "DEGRADED"},
        {nodeId: "peer_f120a", status: "STALE"},
        {nodeId: "peer_4fe22", status: "ACTIVE"},
        {nodeId: "peer_6aa90", status: "ACTIVE"},
      ],
      directEdges: [
        {from: "local", to: "peer_9x23a", status: "CONNECTED"},
        {from: "local", to: "peer_71ab2", status: "CONNECTED"},
        {from: "local", to: "peer_c8d31", status: "DEGRADED"},
        {from: "local", to: "peer_6aa90", status: "CONNECTED"},
      ],
      desiredEdges: [
        {from: "local", to: "peer_3d9f0", status: "PENDING"},
        {from: "local", to: "peer_b4c8d", status: "PENDING"},
        {from: "local", to: "peer_4fe22", status: "PENDING"},
      ],
    },
    relay: {status: "DISABLED", localAddress: "", activeConnections: 0, configured: false, connected: false, relayIdentity: "", authorized: false, activeRouteUsage: 0},
  },
  diagnostics: {
    schemaVersion: "v1",
    reportId: "doc-mock-001",
    projectId: project.id,
    timestampEpochMillis: Date.parse("2026-09-10T02:49:00Z"),
    overallStatus: "DEGRADED",
    criticalCount: 0,
    errorCount: 0,
    warningCount: 1,
    infoCount: 1,
    cleanupRecommended: false,
    reconciliationRecommended: false,
    repairAvailable: false,
    findings: [
      {code: "CAPABILITY_TIMEOUT", severity: "WARNING", confidence: "0.92", summary: "Capability request timeout on code-executor-02", explanation: "The capability check did not complete within the configured timeout.", affectedResourceType: "Agent Executor (code-executor-02)", repairSupported: false, recommendation: "Verify local socket connectivity or increase timeout"},
      {code: "NODE_SYNC_LAG", severity: "INFO", confidence: "0.98", summary: "Node synchronization lag", explanation: "The node is reporting a small synchronization delay while peers remain reachable.", affectedResourceType: "Telemetry Node", repairSupported: false, recommendation: "no_action"},
    ],
  },
};
